name: text-to-cypher
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - neo4j
    - crewai==0.51.1
    - crewai-tools==0.4.26
    - langchain==0.2.12
    - langchain-openai==0.1.20
    - pyautogen
    - python-dotenv
    - openai-agents