name: text-to-cypher
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      # Core LLM + vector
      - langchain
      - langchain-community
      - langchain-openai
      - langgraph
      - openai

      # Neo4j live agent
      - neo4j

      # Web / API
      - fastapi
      - uvicorn

      # Utilities
      - python-dotenv